/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-05-10 16:26:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.producto.negocio.*;

public final class pagina_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("com.producto.negocio");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>CarpiCool</title>\r\n");
      out.write("<link href=\"estilos.css\", rel=\"stylesheet\",text=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"imagen\">\r\n");
      out.write("        <div class=\"contenido\">\r\n");
      out.write("            <header class=\"cuadro\">\r\n");
      out.write("                <h1 class=\" titulo\"> CARPICOOl</h1>\r\n");
      out.write("            </header>\r\n");
      out.write("            <nav >   \r\n");
      out.write("                <ul class=\"do\">\r\n");
      out.write("                <li class=\"option\"> <a href=\"#m1\" class=\"lor\">Informacion</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"option\"> <a href=\"#m2\" class=\"lor\">Registro</a></li>\r\n");
      out.write("                <li class=\"option\"> <a href=\"#m3\" class=\"lor\">Ingreso de productos</a></li>\r\n");
      out.write("                <li class=\"option\"> <a href=\"#m4\" class=\"lor\">mercado</a></li>\r\n");
      out.write("                <li class=\"option\"> <a href=\"#m5\" class=\"lor\">Buscar producto</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"m1\" class=\"mensaje\">Quienes Somos</div>\r\n");
      out.write("        <div id=\"m2\" class=\"mensaje\">\r\n");
      out.write("            <div class=\"cuadro2\">\r\n");
      out.write("                <label class=\"opt\"> Nombre: <input type=”text” name=”txtNombre”/> </label>\r\n");
      out.write("                <label class=\"opt\"> Cedula: <input type=”text” name=”txtCedula”/></label>  \r\n");
      out.write("                <label class=\"opt\"> Estado Civil: <select name=\"cmbECivil\">  \r\n");
      out.write("                    <option value=\"Soltero\">Soltero</option> \r\n");
      out.write("                    <option value=\"Casado\">Casado</option> \r\n");
      out.write("                   <option value=\"Divorciado\">Divorciado</option> \r\n");
      out.write("                    <option value=\"Viudo\">Viudo</option> \r\n");
      out.write("                       </select> </label>    \r\n");
      out.write("                       <label class=\"opt\">Residencia:\r\n");
      out.write("                        <input type=\"radio\" name=\"rdResidencia\" value=\"Sur\"/>Sur   \r\n");
      out.write("                        <input type=\"radio\" name=\"rdResidencia\" value=\"Norte\"/>Norte \r\n");
      out.write("                        <input type=\"radio\" name=\"rdResidencia\" value=\"Centro\"/>Centro </label> \r\n");
      out.write("                        <label class=\"opt\"> Foto:\r\n");
      out.write("                        <input type=\"file\" name=\"fileFoto\" accept=\".jpg, .jpeg, .png\"  />\r\n");
      out.write("                       </label>  \r\n");
      out.write("                       <label class=\"opt\"> Mes y año de nacimiento <input type=\"month\" name=\"fecha\"/> \r\n");
      out.write("                       </label>  \r\n");
      out.write("                       <label class=\"opt\"> Color:\r\n");
      out.write("                        <input type=\"color\"  name=\"color\" value=\"red\">\r\n");
      out.write("                       </label>\r\n");
      out.write("                       <p >\r\n");
      out.write("                        <input type=\"submit\"  value=\"Enviar\" >\r\n");
      out.write("                        <input type=\"reset\"  value=\"Restablecer\" ></p>\r\n");
      out.write("            </div>       \r\n");
      out.write("        </div> \r\n");
      out.write("        <div id=\"m3\" class=\"mensaje\">\r\n");
      out.write("         <div class=\"cuadro2\">\r\n");
      out.write("          <h2> Registro del producto</h2>\r\n");
      out.write("          <form action=\"respuesta.jsp\" method=\"post\">\r\n");
      out.write("        <label class=\"opt\">Codigo: <input type=\"text\" name=\"rCodigo\"></label>\r\n");
      out.write("        <label class=\"opt\">Categoria: <input type=\"text\" name=\"rCategoria\"></label>\r\n");
      out.write("        <label class=\"opt\">Nombre: <input type=\"text\" name=\"rNombre\"></label>\r\n");
      out.write("        <label class=\"opt\">Cantidad:<input type=\"text\" name=\"rCantidad\"></label>\r\n");
      out.write("        <label class=\"opt\">Precio:<input type=\"text\" name=\"rPrecio\"></label>\r\n");
      out.write("        <label class=\"opt\">Foto: <input type=\"file\" name=\"rFoto\" accept=\".jpg, .jpeg, .png\"  /></label>\r\n");
      out.write("        <input type=\"submit\" value=\"Guardar\"/>\r\n");
      out.write("        <input type=\"reset\" value=\"Cancelar\"/>\r\n");
      out.write("        </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"m4\" class=\"mensaje\">\r\n");
      out.write("        ");
producto p=new producto();
        out.print(p.consultarTodo());
        String productId = request.getParameter("cod");
        
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"m5\" class=\"mensaje\">\r\n");
      out.write("        <form action=\"categoria.jsp\" method=\"post\">\r\n");
      out.write("          <label> Pongala la categoria:<input type=\"text\" name=\"rcat\"></label>\r\n");
      out.write("          <input type=\"submit\" value=\"Ingresar\">\r\n");
      out.write("          <input type=\"reset\" value=\"Cancelar\">\r\n");
      out.write("        </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <footer class=\"footer\"> Para mas información llamar al numero: 023213123213</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
